### ISSUE TITLE
RFC: Transitioning from CRA(Craco) to Vite

### ISSUE THREAD

**Issue by Zach-ixo** [ixofoundation/ixo-webclient#1354]
This RFC (Request for Comments) is intended to kickstart a discussion about this potential transition. We welcome input, feedback, and insights from the community to make an informed decision.

**Proposed Changes:**

**Migration from CRA to Vite:** The primary change would involve migrating our project setup from CRA to Vite. This includes updating the build and development workflow, as well as the necessary configuration adjustments.
Reasons for Transition:

**Development Speed**: Vite's native ES modules and optimized development server could potentially lead to faster development iterations and quicker hot module replacement.
**Performance**: Vite's approach to bundling and loading could result in smaller bundle sizes and improved loading times for our application.
**Customization**: Vite offers a more flexible configuration setup compared to CRA, allowing us to tailor the build process to our specific needs.
**Community and Maintenance**: Vite has gained traction in the React ecosystem, and its community is growing. This could lead to better support and future enhancements. While CRA is dying a slow death.

**Discussion Points:**

Have you worked with Vite before? What was your experience like?
Are there any specific concerns or potential challenges in transitioning to Vite?
How can we ensure a smooth migration process for existing contributors and newcomers?
What are your thoughts on Vite's development speed and performance compared to CRA?
Are there any specific features or optimizations in CRA that we should consider in our decision?
How might the transition impact our overall development workflow and CI/CD pipeline?
Are there any potential benefits or drawbacks we might have overlooked?
Any insights or lessons learned from other projects that have transitioned from CRA to Vite?

**Next Steps:**

Participate in the discussion to gather feedback, insights, and concerns.
Evaluate the feasibility of the transition based on the feedback received.
Create a plan for the transition, including testing, migration steps, and communication.

@Michael-Ixo @Pieter-Ixo

**Comment by Michael-Ixo** [comment]
@Zach-ixo my personal experience is that vite can be faster than cra, however I'm just a bit cautious to move over such a big project. With that being said I support the transition and think it would be beneficial

**Comment by Zach-ixo** [comment]
Moved from CRA to NextJS
