### ISSUE TITLE
Revert some of commit a0be00a

### ISSUE THREAD

**Issue by migueldingli1997** [ixofoundation/ixo-webclient#386]
The hard-coded `evaluatorPayPerClaim` introduced in commit a0be00a can now be removed as the template has been updated to no longer require this value. At the time of writing, this involves lines 67-81 of the `src/modules/Entities/CreateEntity/CreateEntity.actions.ts` file.

**Comment by markwilliams0828** [comment]
It was fixed by removing `evaluatorPayPerClaim` .
