### ISSUE TITLE
Update getting started guide in README

### ISSUE THREAD

**Issue by wip-abramson** [ixofoundation/ixo-webclient#611]
Current guide to getting started appears out of date.

Should include copyinig the .env.example file to .env

But the current example.env file does not actually work. At least this URL is incorrect - https://block_sync_pandora.ixo.world/

Note also links to IXO Module and IXO Keyserver both seem to go to this https://github.com/wmonk/create-react-app-typescript

**Comment by demondayza** [comment]
@wip-abramson thanks for this! This is being rectified along with better documentation elsewhere

**Comment by demondayza** [comment]
Cleared.
