### ISSUE TITLE
When not logged in did:ixo:DNBRbdzUsQHcQaRBsX1MR9 crashes when buy attempted

### ISSUE THREAD

**Issue by demondayza** [ixofoundation/ixo-webclient#748]
When attempting to issue a buy while not logged in, the screen will crash

**Comment by markwilliams0828** [comment]
I think When not logged in for `any bond did` crashes when buy attempted?

**Comment by alwyn-ixo** [comment]
> I think When not logged in for `any bond did` crashes when buy attempted?

@demondayza can you see this comment?
I will also have a look at recreating this issue with another bond did...

**Comment by markwilliams0828** [comment]
Review request: https://github.com/ixofoundation/ixo-webclient/pull/760
