### ISSUE TITLE
Need to show the bond state and hatch price in the UI

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#749]

**Comment by elite0226** [comment]
hatch price is from `function_parameters.S0`?
What is the denom for hatch price?
I guess it's reserve token's denom, right?

**Comment by alwyn-ixo** [comment]
> hatch price is from `function_parameters.S0`? What is the denom for hatch price? I guess it's reserve token's denom, right?

@wgmouton Do you perhaps know?

**Comment by elite0226** [comment]
Where to display the Hatch price?

**Comment by steveixo** [comment]
Hatch price is d0.  this is the initial amount to raise
d0 should be in the reserve currency

S0 in this context is the initial supply, which is the number of tokens in the hatch sale based on the initial price.

**Comment by steveixo** [comment]
for hatch, displaying d0 and the currency as well as amount of d0 left to purchase to hatch would be epic.  that i guess is d0 - reserve,   d0>0

**Comment by steveixo** [comment]
Where to display bond status and hatch status.  - please be creative for now.  having on the screen and working is more important at this moment that where we place it.  we can look at that on Tuesday

**Comment by demondayza** [comment]
@goldenstar07 we need to add the wording "Hatch price:" in front of the hatch price to close this up.

**Comment by demondayza** [comment]
Hatch amount should not show when bond is hatched.

**Comment by markwilliams0828** [comment]
![Uploading image.png…]()

**Comment by markwilliams0828** [comment]
![image](https://user-images.githubusercontent.com/64268193/166473885-4e80e2ca-b6d5-4358-878a-849c7a787481.png)
