### ISSUE TITLE
Alpha needs to show the system alpha

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#751]

**Comment by markwilliams0828** [comment]
The system alpha is displaying the value which is fetched from the bonds endpoint correctly.

The reason why it's displaying **zero** in bonds dashboard is the system_alpha value is being very small for this [bond](https://testnet.ixo.world/ixo/bonds/did:ixo:Ft4NbxcsXyBGczyQpS39Mf) as an example.
systemAlpha: "0.000007342143906020"

**Comment by alwyn-ixo** [comment]
> The system alpha is displaying the value which is fetched from the bonds endpoint correctly.
> 
> The reason why it's displaying **zero** in bonds dashboard is the system_alpha value is being very small for this [bond](https://testnet.ixo.world/ixo/bonds/did:ixo:Ft4NbxcsXyBGczyQpS39Mf) as an example. systemAlpha: "0.000007342143906020"

@wgmouton Is this normal for a bond; i.e. to have such a small value?
Is there a strict range or should it be coded to show 18 decimals?
