### ISSUE TITLE
Sells disabled needs a tooltip

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#753]

**Comment by elite0226** [comment]
`Sell` button display depends on `allow_sells` property from endpoint, right?
And what text would be shown to users in tooltip?

**Comment by steveixo** [comment]
For the moment, do not worry about sell.  We will try and exclude it from the demo. We will discuss where we are on Tuesday and decide on this.

**Comment by demondayza** [comment]
@elite0226 for when we implement this, the text in the tooltip based on the allow_sells status would be "Sells have been disabled by the bond creator"
