### ISSUE TITLE
Buys disabled needs a tooltip

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#754]

**Comment by elite0226** [comment]
What is the condition for disable/enable `Buy` button?
And what text would be shown to users in tooltip?

**Comment by steveixo** [comment]
The buy button, will require the user to have keysafe logged in and have the correct currency in sufficient volumes. 

I would suggest that no keysafe logged in, it is greyed out.  maybe a tip saying login or a link.

currency, it currently is empty if the currency is not available, so maybe a tool tip to say - go get required currency. keep it simple

if there is not enough currency, I think the maths already handles it

**Comment by steveixo** [comment]
Text in tooltip.   brief and to the point.  we can worry about what actual text is next week.  having a tooltip appear and working is far more important for Tuesday
