### ISSUE TITLE
Max supply needs to be shown somewhere in the buy flow prior to buys happening

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#758]

**Comment by elite0226** [comment]
![image](https://user-images.githubusercontent.com/50171204/166007499-b8f9d128-9e0c-48be-a792-2be021dd9587.png)
Max Available Supply limit is being shown in the modal.

**Comment by alwyn-ixo** [comment]
@elite0226 Does it become less than 1000.00B (in this example) as people Buy?
For example, if person 1 buys 543.00B then person 2 must see 457.00B MAX Available.

**Comment by steveixo** [comment]
correct.

**Comment by steveixo** [comment]
this screen grab looks nice. just the alteration stated by Alwyn.  There are other changes, but We will not consider discus them until this is nice and smooth

**Comment by steveixo** [comment]
The interesting thing in the hatch phased, the price is the price and the % above quoted price is not a factor. All tokens should be same value unless I am very mistaken.  

Once the bond is hatched and the bonding curve comes into effect, then the percentages above quoted price are required. 

This is an observation, do not change anything on this.  It still needs workshopping as it is more complex, as it also has an effect on a failed bond
