### ISSUE TITLE
FAILED Change claim type in Chimple Project to  Credit Note in did:sov:GV1B2NuW5MvczufYCtCTfk

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#772]
Please speak to Andrew for further info.

**Comment by markwilliams0828** [comment]
@demondayza Can you please kindly let me get the specific details for this issue?

**Comment by demondayza** [comment]
@goldenstar07 please confirm the exact steps to reproduce with shaun, I am not seeing a obvious way to reproduce.

**Comment by demondayza** [comment]
@elite0226 please speak with Shaun to understand how to reproduce

**Comment by ig-shaun** [comment]
There is nothing further to be done on this issue and it can be closed. 
The cause of this issue has been understood as being as a result of edit entity not being possible after the entity moves from pending state, which is restricted at the level of the blockchain.

**Comment by demondayza** [comment]
@ig-shaun thank you. I am closing this issue accordingly.
