### ISSUE TITLE
Fix glitch in Claims submission chart timeline (showing wrong time-period)

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#774]

**Comment by elite0226** [comment]
Need a specific entitydid and more detail for this issue please.

**Comment by demondayza** [comment]
@alwyn-ixo please link a example entity

**Comment by demondayza** [comment]
@elite0226 did:ixo:Xcum22jXBqZdmfDehi1giB this has the scales wrong with the claims submissions

**Comment by elite0226** [comment]
![image](https://user-images.githubusercontent.com/50171204/169074061-1ae7e4d6-a42a-47e0-93d1-52ab4be11a8a.png)

**Comment by elite0226** [comment]
This issue is resolved by https://github.com/ixofoundation/ixo-webclient/issues/836 which Audricus worked on?
