### ISSUE TITLE
On entity document update we are hitting “capability not found for project”

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#775]

**Comment by elite0226** [comment]
I think this issue has been resolved by Audricus several days ago?
Also I tried and got success at updating an entity today.

**Comment by demondayza** [comment]
@elite0226 can you link the pull request and I can close the ticket

**Comment by elite0226** [comment]
@demondayza I think this has already been merged to dev.

**Comment by demondayza** [comment]
@elite0226 please link the old merge so I can check it

**Comment by markwilliams0828** [comment]
@demondayza @elite0226 Updating an **Project** entity success but updating an **Investment** entity failed.
Shared the examples on Slack.

https://ixofoundation.slack.com/archives/C03CXRWPVU2/p1652132884382579
https://ixofoundation.slack.com/archives/C03CXRWPVU2/p1652135245609549
