### ISSUE TITLE
Chart price values to be checked against blocksync price api 

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#776]

**Comment by elite0226** [comment]
I believe the chart price values are matched to data from blocksync api

**Comment by demondayza** [comment]
@elite0226 please confirm and I can close the ticket

**Comment by elite0226** [comment]
Yes. I don't see any problem for about this.

**Comment by alwyn-ixo** [comment]
The chart does not show the values returned from BlockSync for Bond DID = did:ixo:Ft4NbxcsXyBGczyQpS39Mf.
Perhaps the axes are not the correct precision?

![image](https://user-images.githubusercontent.com/100694789/169285946-2de126be-db52-4efc-a015-c248c082f421.png)

https://blocksync-pandora.ixo.world/api/bonds/getPriceHistoryByBondDid/did:ixo:Ft4NbxcsXyBGczyQpS39Mf response:
{
    "_id": "6141c2b0b00631001af0e2d4",
    "priceHistory":
    [
        {
            "price": "1000.000000000000000000",
            "time": "2021-09-15T09:53:51.969Z"
        },
        {
            "price": "2999.999999999999978793",
            "time": "2022-04-29T10:35:21.287Z"
        }
    ]
}

**Comment by alwyn-ixo** [comment]
Perhaps the axes is not the correct precision?

**Comment by elite0226** [comment]
@alwyn-ixo I see what's wrong here.
The prices are being calculated to division of 1 million.

So `price in Blocksync`: 1000.000 represents `price in UI`: 0.001
`price in Blocksync`: 2999.999 represents `price in UI`: 0.0029999

0.001 and 0.002999 are quite small and that's why the chart is looking like for this bonddid.

**Comment by alwyn-ixo** [comment]
@elite0226 I think we really want to show these prices on the chart, so can you please change the division to fall in your y-axis range?
For example, 2,999.999 / 1,000, instead of 2,999.999 / 1,000,000.

**Comment by elite0226** [comment]
/projects/did:ixo:KoCgGNSAirEeS8TaLXxUEm/bonds/did:ixo:Ft4NbxcsXyBGczyQpS39Mf/detail/overview
