### ISSUE TITLE
Project outcome payments are needed on a new table 

### ISSUE THREAD

**Issue by demondayza** [ixofoundation/ixo-webclient#782]

**Comment by markwilliams0828** [comment]
Specific api endpoints are needed for displaying Outcome payments table.

**Comment by markwilliams0828** [comment]
https://chimple.ixo.earth/projects/did:ixo:Xcum22jXBqZdmfDehi1giB/bonds/did:ixo:Ft4NbxcsXyBGczyQpS39Mf/detail/outcomes

In some cases, we have the UI for outcome

**Comment by demondayza** [comment]
@goldenstar07 a new blocksync api is available, we are just waiting for it to sync

**Comment by alwyn-ixo** [comment]
https://www.figma.com/file/rTQomLMpE93nz1kIGMQ9VA/Webclient?node-id=461%3A4061

**Comment by vaibhavphutane** [comment]
@alwyn-ixo currently 
We already have an outcomes table design developed with hardcoded data, we will need to have an API endpoint for fetching the data.

**Comment by demondayza** [comment]
@vaibhavphutane Heres a example api @alwyn-ixo will need to get you a valid did https://blocksync-pandora.ixo.world/api/bond/get/outcomepayments/
