### ISSUE TITLE
Alpha card should have different values depending on bond state

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#788]
If the bond has not yet been hatched, the Alpha card must show the Hatch Amount left and Hatch Price.

**Comment by markwilliams0828** [comment]
Just check in here.
If the bond has not yet been hatched, the Alpha card shouldn't display the `systemAlpha` and display only Hatch Amount left and Hatch Price,
And If the bond has been hatched, there is no display of Hatch Price and the Alpha Card should display only `systemAlpha` on it, right?

**Comment by markwilliams0828** [comment]
![image](https://user-images.githubusercontent.com/64268193/166853405-b765e678-63ed-4355-ae81-7d88705ff57f.png)
![image](https://user-images.githubusercontent.com/64268193/166853419-30f16c6d-15f1-4281-8cae-d3d8108a11e7.png)

Just need a confirmation for this.
