### ISSUE TITLE
User not logged in and clicking on Reserve card shows white screen

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#792]
https://idcc.ixo.earth/projects/did:ixo:WrAtYQxytJGdZCh2SavztC/bonds/did:ixo:RFuU7PuNdvY1UyBTHhTr7b/detail/overview

Happens in this specific case but not always.

**Comment by goldenstar07** [comment]
I don't see any errors or white screens when navigating to the Reserve card for this entity.

**Comment by alwyn-ixo** [comment]
https://idcc.ixo.earth/projects/did:ixo:5fWRipkrNpYsSndSQABCUE/bonds/did:ixo:2w77BNx7DSH7pjv8fVgdUE/detail/overview

Another example

**Comment by alwyn-ixo** [comment]
@goldenstar07 @elite0226 
Can you please confirm that this is working?
There are still white screens coming up (see the previous comment for a new example)

**Comment by alwyn-ixo** [comment]
tested
