### ISSUE TITLE
Bond Transaction Table Bugs

### ISSUE THREAD

**Issue by demondayza** [ixofoundation/ixo-webclient#810]
Quantity numbers must be thousands coma-separated
 No Price displays - is this because the price is <0.00. It does not make sense, as the price should at least be a few cents.
 The number of EDU tokens to purchase for each XUSD is enormous. Is this an error on the module or front-end display?

**Comment by demondayza** [comment]
Refer to web-91 on youtrack!

**Comment by elite0226** [comment]
This has been resolved in yesterday's PR. 🙂

**Comment by demondayza** [comment]
@elite0226 Great, do me a favour resolve the deepscan issues so I can merge any fixes

**Comment by elite0226** [comment]
@demondayza Is there other reason for this issue opened?
