### ISSUE TITLE
Check that the SDG selector on Assets Explorer are showing the correct filter values.

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#828]
![image](https://user-images.githubusercontent.com/100694789/169091594-e64a9ef2-75b3-4395-9e52-6df42168385f.png)

**Comment by elite0226** [comment]
I see nothing is wrong on here.
What specific issues are on this screen?

**Comment by alwyn-ixo** [comment]
@elite0226 The selectable cards inside the SDG pop-up are not correct, I believe.
Non-Fungible Token, Option, Contract, Ownership Certificate, etc. are not some of the 17 SDGs.
![image](https://user-images.githubusercontent.com/100694789/169109250-5e87afab-ff97-4395-ae62-42fd739ce965.png)

**Comment by elite0226** [comment]
These SDGs are from https://github.com/ixofoundation/ixo-webclient/blob/dev/configs/testzone/config.json#L4948
testzone / config file

**Comment by alwyn-ixo** [comment]
Thx - let me confirm and get back to you - putting this Issue on hold for now.
