### ISSUE TITLE
Agents page shows nothing - should show the one authorised Agent

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#837]
![image](https://user-images.githubusercontent.com/100694789/169242287-ece5e7dd-354f-449a-8aa5-a34f6c436cdf.png)

![image](https://user-images.githubusercontent.com/100694789/169242358-dc158e6f-67f4-400d-bd0c-06bafae779ab.png)

**Comment by markwilliams0828** [comment]
I think why there is no agents display is your account is not a project creator.

**Comment by vaibhavphutane** [comment]
Hey @alwyn-ixo 
The agent tab is only visible for the role `Agent.Owner`, where userId and creator id matches.
We have checked the following snippet and came to this conclusion.
![image](https://user-images.githubusercontent.com/14000470/170522389-f49d5869-a01c-4af2-8cf2-51532a6ec909.png)
