### ISSUE TITLE
Create a MyStake tab with a filtered version of the Transactions against the Bond

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#841]
Use the existing Figma designs

**Comment by alwyn-ixo** [comment]
https://blocksync-pandora.ixo.world/transactions/listTransactionsByBondDid/did:ixo:Ft4NbxcsXyBGczyQpS39Mf
Use this (or similar) API call to return all transactions against the Bond and filter by "buyer_did" for the logged-in user.

Similar look-and-feel to the Last Price tab but rather look at the Figma design..
![image](https://user-images.githubusercontent.com/100694789/169299626-c6d0d780-131f-49cf-8344-1e87377d48c8.png)

**Comment by elite0226** [comment]
I think maybe the MyStake tab should be active to select only there is a keysafe logged in?

**Comment by elite0226** [comment]
How do we display the chart for the MyStake tab?

**Comment by alwyn-ixo** [comment]
> I think maybe the MyStake tab should be active to select only there is a keysafe logged in?

@elite0226 Correct; that makes good sense.
