### ISSUE TITLE
Whitescreen on overview page

### ISSUE THREAD

**Issue by demondayza** [ixofoundation/ixo-webclient#854]
Overview page -> https://chimple.ixo.earth/projects/did:ixo:Xcum22jXBqZdmfDehi1giB/bonds/did:ixo:Ft4NbxcsXyBGczyQpS39Mf/detail/overview  has a white screen issue. 

Uncaught TypeError: n().account.userInfo is null

**Comment by vaibhavphutane** [comment]
Had a look at this one it seems to be fixed, @alwyn-ixo 
![image](https://user-images.githubusercontent.com/14000470/171211613-81be9a59-c2c6-4b2d-92be-3e02cf5b14d0.png)

**Comment by demondayza** [comment]
Thanks @vaibhavphutane
