### ISSUE TITLE
EdHeroes demo preparation (Tue, May 31) - New Sector

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#876]
Please create a new Sector with these details: (to be confirmed)
- "ddoTag": "EdHeroes"
- "color": "#FF00FF"
- "image": "edheroes.png"
- "title": "EdHeroes"
- "subTitle": "Singapore"

{
          "@context": "https://schema.idcc.hk/sector",
          "id": "https://schema.idcc.hk/sector",
          "@type": "HeaderOverride",
          "ddoSector": "Sector",
          "ddoTag": "IDCC",
          "color": "#FF00A8",
          "image": "idcc_hero.png",
          "title": "IDCC",
          "subTitle": "Hong Kong",
          "indicators": [
            {
              "@type": "Indicator",
              "indicatorLabel": "Candidates",
              "indicatorSource": "https://metrics.ixo.foundation/relayer_candidates"
            },
            {
              "@type": "Indicator",
              "indicatorLabel": "Launched",
              "indicatorSource": "https://metrics.ixo.foundation/relayers_launched"
            },
            {
              "@type": "Indicator",
              "indicatorLabel": "Total Votes",
              "indicatorSource": "https://metrics.ixo.foundation/relayer_launchpad_votes"
            }
          ]
        }
      ]
    },

**Comment by elite0226** [comment]
`edheroes.png` need image design.
