### ISSUE TITLE
DAO (Cell) Explorer Cards

### ISSUE THREAD

**Issue by elite0226** [ixofoundation/ixo-webclient#879]
Implement Cell cards in the Cell Explorer view.

Uses the same card layout and size as the cards in Projects Explorer.
Shields are labelled according to the configuration name for cells, such as `DAO`
Label values are:
\- `Group` for DAOs that use the Group Module
\- `Treasury` for DAOs that use the Cosmwasm Smart Contract multi-sig.
\- It is possible for a cell to be both a DAO-Group and DAO-Treasury and if this is the case, both shields will display.

The headline indicator can optionally be created to display
\- Claim (same functionality as Project)
\- Members
\- Accounts
Add the 2 new values `Members` and `Accounts` to the Headline Indicator enum selector in the Create Cell configuration.

`Members` are unique Agent DIDs approved with ANY role (IA, SA, EA, ...)

`Accounts` are the number of accounts in a Group or in a Multisig.

If the headline is `Accounts` this will Get the number of account-holders by Blocksync query from the following endpoint: **TBD**
If the headline is `Members` this will Get the number of account-holders by Blocksync query from the following endpoint: **TBD** 

If the Headline indicator is of one of these 2 types, there is no denominator value displayed and the Progress bar is not visible (to maintain consistent card size, just change the bar colour to match the card colour so it is not visible).

**Comment by elite0226** [comment]
here is the styling https://www.figma.com/file/rTQomLMpE93nz1kIGMQ9VA/Webclient?node-id=9767%3A3798
This may not be accurate in terms of card size etc. Please use the same card layout dimensions as already implemented for Projects.
Remember, there also needs to be a Shield for the Status (e.g. Status: Created). The colour of this shield can match same as project cards.

Note the container space for multiple shields should fit all variations of the shields and if this spills into a second line, this should not distort the card size or position of the other elements.

**Comment by vaibhavphutane** [comment]
Hey @alwyn-ixo 
We have updated the DAOs card design as per the figma mockup, we need to have API endpoint information to get actual data from block sync. can please share the API details if possible.
![image](https://user-images.githubusercontent.com/14000470/171044048-7d1cedf2-6cb5-47d6-9b3b-189ee0d97506.png)
PS: all current changes are present in `IXO-879-DAO-card`

**Comment by alwyn-ixo** [comment]
@demondayza @vaibhavphutane 
Hi Andrew - can we pls discuss tmw whether there are APIs available for this feature?

**Comment by demondayza** [comment]
@alwyn-ixo absolutely, and if we dont have any we will make em.
