### ISSUE TITLE
No toast notification after authorising an agent

### ISSUE THREAD

**Issue by elite0226** [ixofoundation/ixo-webclient#884]
## Scope
https://ixo.youtrack.cloud/issue/WEB-96

Success
![image](https://user-images.githubusercontent.com/14000470/171464199-1a746aab-323c-4bcf-a81e-c98dd6f5315f.png)

**Comment by vaibhavphutane** [comment]
@alwyn-ixo Added the toast messages on success and failure for sign, tested with  `/projects/did:ixo:D17XFkkhdNAF1BMAEiP1BW/detail/agents`
