### ISSUE TITLE
Bonds: Reference Pricing Curves

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#887]
Please add two additional curves to the Price graph for a bond so that investors may view the standard curve alongside the actual Optimistic and Pessimistic curves.

![Bonds Pricing Reference Curve](https://user-images.githubusercontent.com/100694789/171253481-bdea0d88-f3b2-4c7f-8b17-69893eef7aa4.jpg)

**Comment by elite0226** [comment]
displaying two curves on the price history chart on the bonds interface?
![image](https://user-images.githubusercontent.com/50171204/171275117-f2fbc773-3c78-447e-90a2-8d915cb4e4a3.png)

Is there any api call's ready for optimistic & pessimistic chart?
Or do I need to implement this with placeholder?

**Comment by alwyn-ixo** [comment]
@elite0226 
There should be 3 curves on the chart: standard + optimistic + pessimistic.
We will provide DIDs for the 2 additional bonds.

**Comment by alwyn-ixo** [comment]
@elite0226 
The Optimistic- and Pessimistic Curves are actually just 2 other bonds' price histories that are displayed on the same chart - to be provided.
The Standard Curve is the formula for the predicted bond prices - to be provided.
