### ISSUE TITLE
Change default filters for Projects on Explorer

### ISSUE THREAD

**Issue by alwyn-ixo** [ixofoundation/ixo-webclient#914]
Given that a user selects EXPLORE in the top left corner 
When they land on the default page for Projects
Then the filter for Project Type has no selections. (currently it has two)
![image](https://user-images.githubusercontent.com/100694789/171717520-f6abc631-fdf6-47fa-8aac-6361fb0e5bd4.png)

![image](https://user-images.githubusercontent.com/100694789/171718418-287ec0c3-d6a4-4713-aed6-2565e9efa6f4.png)

**Comment by vaibhavphutane** [comment]
@alwyn-ixo this issue has been fixed by @elite0226

**Comment by vaibhavphutane** [comment]
@alwyn-ixo this issue has been solved.
